# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'AUTOAVES_REFERRAL' do
pod 'Google/Analytics'

end

target 'AUTOAVES_REFERRALTests' do

end

